#!/usr/bin/env bash

# like cd but fuzzy
cf() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
    -o -type d -print 2>/dev/null | fzf +m) &&
    cd "$dir" || return
}

# sync caravan repo
push-nix() {
  cd ~/.config/nixpkgs
  git add .
  git commit -a -m "$1"
  git push
  cd -
}

sync-nix() {
  cd ~/.config/nixpkgs
  git add .
  git stash
  git checkout main
  git pull origin main
  git stash pop
  home-manager switch
  push-nix "sync-nix performed on $(date)"
  cd -
}

kc-patch-secret() {
  local value
  value=$(echo "$3" | base64)
  kubectl patch secret "$1" --type='json' -p='[{"op" : "replace" ,"path" : '$2' ,"value" : '$value'}]'
}

kc-decode-secret() {
  local value
  value=$(kubectl get secret "$1" -o jsonpath="{$2}")
  echo "$value" | base64 -d
}

gitra() {
  url="git@github.com:$1/$2.git"
  git remote add $1 $url
}

gcloud-auth() {
  gcloud init
  gcloud auth login
  gcloud auth application-default login
  gcloud auth configure-docker us-central1-docker.pkg.dev,asia-northeast1-docker.pkg.dev,europe-west1-docker.pkg.dev
}

new-cosign-image() {
  docker pull $1
  docker tag $1 $2/$1
  docker push $2/$1
  cosign attest --predicate $HOME/.tmp/cosign/predicate.json --type custom $2/$1 --key $CK
}

## Tailscale: deploy ts-recorder
ts-rec() {
  mkdir -p "$HOME/.config/dev"
  current="$(cat "$HOME/.config/dev/recorder-version" 2>/dev/null)"
  if [[ $current =~ ^[0-9]+$ ]]; then
    local next=$((current + 1))
  else
    local next=1
  fi
  ctx="$(k config current-context)"
  echo "$next" >"$HOME/.config/dev/recorder-version"
  echo "deploying $next"
  if [ $ctx = "kind" ] || [ $ctx = "kind-kind" ]; then
    local base=localhost:5001
    local platform=""
  else
    local base=europe-west2-docker.pkg.dev/tailscale-sandbox/chaosinthecrd
    local platform="flyio"
  fi

  local rrepo="$base/tsrecorder"

  old=$(pwd)
  cd /Users/chaosinthecrd/Git/corp/cmd/tsrecorder
  PUSH=true TAGS=$next REPOS=$rrepo VERSION_GIT_HASH=foo VERSION_PATCH=wi VERSION_MINOR=wih VERSION_MAJOR=wah VERSION_EXTRA_HASH="blah" /Users/chaosinthecrd/Git/corp/cmd/tsrecorder/publish.sh
  cd $old

  if [ "$ctx" = "kind" ] || [ "$ctx" = "kind-kind" ]; then
    echo "loading image $repo:$next into kind"
    docker pull "$rrepo:$next"
    kind load docker-image "$rrepo:$next"
  fi

  echo "- $rrepo:$next"
}

## Tailscale: deploy with helm
ts-helm() {
  mkdir -p "$HOME/.config/dev"
  next="$(cat "$HOME/.config/dev/container-version" 2>/dev/null)"
  ctx="$(kubectl config current-context)"

  if [ $ctx = "kind" ] || [ $ctx = "kind-kind" ]; then
    local base=localhost:5001
    local platform=""
  else
    local base=europe-west2-docker.pkg.dev/tailscale-sandbox/chaosinthecrd
    local platform="flyio"
  fi

  local orepo="$base/k8s-operator"
  local trepo="$base/tailscale"
  local rrepo="$base/tsrecorder"
  local prepo="$base/k8s-proxy"

  if [ "$ctx" = "kind" ] || [ "$ctx" = "kind-kind" ]; then
    echo "loading image $repo:$next into kind"
    docker pull "$orepo:$next"
    kind load docker-image "$orepo:$next"
    docker pull "$trepo:$next"
    kind load docker-image "$trepo:$next"
    docker pull "$prepo:$next"
    kind load docker-image "$prepo:$next"
    docker pull "$rrepo:$next"
    kind load docker-image "$rrepo:$next"
  }

  # extra+="--set-string operatorConfig.image.repository=$repo "
  # extra+="--set-string operatorConfig.image.tag=$next "
  # extra+="--set-string proxyConfig.image.repository=$repo "
  # extra+="--set-string proxyConfig.image.tag=$next "

  case "$ctx" in
  gke_*) # Matches GKE context names like gke_project-zone-cluster
    local hostname=gke-operator
    ;;
  arn:aws:eks:*) # Matches EKS context names starting with this ARN prefix
    local hostname=eks-operator
    ;;
  kind-*) # Matches Kind cluster names like kind-test
    local hostname=kind-operator
    ;;
  *)
    local hostname=operator
    ;;
  esac
  local root="$HOME/Git/tailscale"
  local localDir="chaosinthecrd"
  echo "deploying helm chart with image:"
  echo "- $orepo:$next"
  echo "- $trepo:$next"
  echo "- $rrepo:$next"
  echo "- $prepo:$next"
  echo "deploying with values:"
  cat -p $root/$localDir/values.yaml
  helm upgrade --install tailscale-operator "$root/cmd/k8s-operator/deploy/chart" \
    --namespace tailscale \
    --create-namespace \
    --values "$root/$localDir/values.yaml" \
    --set-string operatorConfig.image.tag="$next" \
    --set-string proxyConfig.image.tag="$next" \
    --set-string operatorConfig.hostname="$hostname" \
    --wait
}

## Kubectl: apply a yaml string
function kapply() {
  # Check if an argument (YAML content) was provided
  if [ -z "$1" ]; then
    echo "Error: You must paste the YAML content as the argument." >&2
    echo "Usage: kapply '... your YAML here ...'" >&2
    return 1
  }

  echo "Applying YAML..."
  # Use ''' "$1"''' to pass the first argument (the YAML string)
  # directly to standard input of kubectl.
  echo "$1" | kubectl apply -f -
}

## Tailscale: deploy all components
ts-deploy() {
  mkdir -p "$HOME/.config/dev"
  current="$(cat "$HOME/.config/dev/container-version" 2>/dev/null)"
  if [[ $current =~ ^[0-9]+$ ]]; then
    local next=$((current + 1))
  else
    local next=1
  fi
  ctx="$(k config current-context)"
  echo "$next" >"$HOME/.config/dev/container-version"
  echo "deploying $next"
  if [ $ctx = "kind" ] || [ $ctx = "kind-kind" ]; then
    local base=localhost:5001
    local platform=""
  else
    local base=europe-west2-docker.pkg.dev/tailscale-sandbox/chaosinthecrd
    local platform="flyio"
  fi

  local orepo="$base/k8s-operator"
  local trepo="$base/tailscale"
  local rrepo="$base/tsrecorder"
  local prepo="$base/k8s-proxy"

  PLATFORM=$platform TAGS=$next REPO=$orepo make -C /Users/chaosinthecrd/Git/tailscale publishdevoperator
  PLATFORM=$platform TAGS=$next REPO=$trepo make -C /Users/chaosinthecrd/Git/tailscale publishdevimage
  PLATFORM=$platform TAGS=$next REPO=$prepo make -C /Users/chaosinthecrd/Git/tailscale publishdevproxy
  old=$(pwd)
  cd /Users/chaosinthecrd/Git/corp/cmd/tsrecorder
  PUSH=true TAGS=$next REPOS=$rrepo VERSION_GIT_HASH=foo VERSION_PATCH=wi VERSION_MINOR=wih VERSION_MAJOR=wah VERSION_EXTRA_HASH="blah" /Users/chaosinthecrd/Git/corp/cmd/tsrecorder/publish.sh
  cd $old

  if [ "$ctx" = "kind" ] || [ "$ctx" = "kind-kind" ]; then
    echo "loading image $repo:$next into kind"
    docker pull "$orepo:$next"
    kind load docker-image "$orepo:$next"
    docker pull "$trepo:$next"
    kind load docker-image "$trepo:$next"
    docker pull "$prepo:$next"
    kind load docker-image "$prepo:$next"
    docker pull "$rrepo:$next"
    kind load docker-image "$rrepo:$next"
  fi

  # extra+="--set-string operatorConfig.image.repository=$repo "
  # extra+="--set-string operatorConfig.image.tag=$next "
  # extra+="--set-string proxyConfig.image.repository=$repo "
  # extra+="--set-string proxyConfig.image.tag=$next "

  case "$ctx" in
  gke_*) # Matches GKE context names like gke_project-zone-cluster
    local hostname=gke-operator
    ;;
  arn:aws:eks:*) # Matches EKS context names starting with this ARN prefix
    local hostname=eks-operator
    ;;
  kind-*) # Matches Kind cluster names like kind-test
    local hostname=kind-operator
    ;;
  *)
    local hostname=operator
    ;;
  esac
  local root="$HOME/Git/tailscale"
  local localDir="chaosinthecrd"
  echo "deploying helm chart with image:"
  echo "- $orepo:$next"
  echo "- $trepo:$next"
  echo "- $rrepo:$next"
  echo "- $prepo:$next"
  helm upgrade --install tailscale-operator "$root/cmd/k8s-operator/deploy/chart" \
    --namespace tailscale \
    --create-namespace \
    --values "$root/$localDir/values.yaml" \
    --set-string operatorConfig.image.tag="$next" \
    --set-string proxyConfig.image.tag="$next" \
    --set-string operatorConfig.hostname="$hostname" \
    --wait
}

reset_registry() {
  # Stop and remove any existing registry container
  echo "Stopping and removing any existing registry container..."
  docker stop registry 2>/dev/null
  docker rm registry 2>/dev/null

  # Run Docker registry with the new certificates
  echo "Deploying the new registry to localhost:5001... (5000 is always used for airplay rubbish...)"
  docker run -d \
    --name registry \
    -p 5001:5001 \
    -e REGISTRY_HTTP_ADDR=0.0.0.0:5001 \
    registry:2

  echo "Registry is deployed at https://localhost:5000"
}
